### ISSUE TITLE
ERROR LOADING PLUGIN

### ISSUE THREAD

**Issue by phpfs** [nferro/homebridge-http-json#1]
Hello!

I get this error trying to use your plugin:

`====================
[8/27/2016, 11:42:54 PM] ERROR LOADING PLUGIN homebridge-http-json:
[8/27/2016, 11: 42:54 PM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:112:14)
    at Array.forEach (native)
[8/27/2016, 11:42:54 PM] 
====================`

Greetings, phpfs

**Comment by phpfs** [comment]
Fixed it and started a pull request :)

Greetings, phpfs
